In [5]:
import random
import numpy as np
import matplotlib.pyplot as plt


In [57]:
y=[0,1]

W=np.array([[2,3],[5,7]])
X=np.array([[1,0],[0,1]])

print(W.shape)

(2, 2)


In [58]:
scores=np.dot(W,X)
print(scores)
print(scores.shape[1])

[[2 3]
 [5 7]]
2


In [59]:
scores[y, np.arange(0, scores.shape[1])]

array([2, 7])

In [12]:
print(type(scores))

<class 'numpy.ndarray'>


In [13]:
np.arange(0,2)

array([0, 1])

In [14]:
scores[[0,1],[0,1]] #scores[0,0] scores[1,1]

array([2, 5])

In [15]:
scores[[0,1]]

array([[2, 3],
       [4, 5]])

In [16]:
print(scores[[0,1]])

[[2 3]
 [4 5]]


In [60]:
cs = np.ones(scores.shape) * scores[y, np.arange(0, scores.shape[1])]
print(cs)

[[2. 7.]
 [2. 7.]]


In [23]:
a=np.array([[1,2],[3,4]])
b=np.array([2,3])

print(a*b)

[[ 2  6]
 [ 6 12]]


In [61]:
score=X.dot(W)
print(score)

[[2 3]
 [5 7]]


In [62]:
score_1=np.exp(score)
print(score_1)

[[   7.3890561    20.08553692]
 [ 148.4131591  1096.63315843]]


In [30]:
T=np.sum(score_1)
print(T)

230.48590215783915


In [63]:
T=np.sum(score_1, axis=1)
print(T)
print(T.shape)

[  27.47459302 1245.04631753]
(2,)


In [64]:
T_1=np.sum(score_1, axis=1, keepdims=True)
print(T_1)
print(T_1.shape)

[[  27.47459302]
 [1245.04631753]]
(2, 1)


In [33]:
A=np.ones((3073,10))
print(A.shape)

(3073, 10)


In [34]:
B=np.ones((500,3073))
print(B.shape)

(500, 3073)


In [37]:
D=B.dot(A)
print(D.shape)

(500, 10)


In [38]:
d=np.dot(B,A)
print(d.shape)

(500, 10)


In [42]:
T[0]

27.47459302211832

In [43]:
Tsum=np.sum(score_1, axis=1)

In [65]:
nor=score_1/T_1
print(nor.shape)
print(nor)

(2, 2)
[[0.26894142 0.73105858]
 [0.11920292 0.88079708]]


In [66]:
score_2=np.exp(score)
print(score_2)

T_2=np.sum(score_2, axis=1, keepdims=True)
print(T_2)
print(T_2.shape)

[[   7.3890561    20.08553692]
 [ 148.4131591  1096.63315843]]
[[  27.47459302]
 [1245.04631753]]
(2, 1)


In [67]:
N=X.shape[0]
print(N)
E=nor[np.arange(N),y]
print(E)

2
[0.26894142 0.88079708]


In [53]:
np.arange(2)

array([0, 1])

In [54]:
score_2[np.arange(N),y]

array([  7.3890561, 148.4131591])

In [68]:
normal=score_2/T_2
print(normal)

[[0.26894142 0.73105858]
 [0.11920292 0.88079708]]


In [70]:
H=normal[np.arange(N),y]
print(H)

[0.26894142 0.88079708]
